apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: altinn-admin
  namespace: alf
  labels:
    team: alf
spec:
  image: {{ image }}
  team: alf
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 30
    periodSeconds: 20
    failureThreshold: 10
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    outbound:
      external:
      {{#each outbound-host}}
        - host: "{{this}}"
      {{/each}}
  maskinporten:
    enabled: {{use-maskinporten}}
    scopes:
      consumes:
        - name: "altinn:serviceowner"
  webproxy: true
  {{#if ingresses}}
  ingresses:
    {{#each ingresses}}
    - "{{this}}"
    {{/each}}
  {{/if}}
  vault:
    enabled: true
  env:
    - name: USE_VAULT_ENV
      value: "true"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
