apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: altinn-admin
  namespace: default
  labels:
    team: alf
spec:
  image: {{ image }}
  team: alf
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  istio:
    enabled: false
  {{#if ingresses}}
  ingresses:
    {{#each ingresses}}
    - "{{this}}"
    {{/each}}
  {{/if}}
  vault:
    enabled: true
  webproxy: true
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
