apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: altinn-admin
  namespace: alf
  labels:
    team: alf
spec:
  image: {{ image }}
  team: alf
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 30
    periodSeconds: 20
    failureThreshold: 10
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 20
    failureThreshold: 10
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        groups:
          - id: "db95e00b-6176-41c8-9d02-4a40cb75652d"
  accessPolicy:
    outbound:
      external:
      {{#each outbound-host}}
        - host: "{{this}}"
      {{/each}}
    inbound:
      rules:
        - application: alf-testapp
          namespace: alf
          cluster: dev-gcp
  maskinporten:
    enabled: {{use-maskinporten}}
    scopes:
      consumes:
        - name: "altinn:serviceowner"
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    {{#each ingresses}}
    - "{{this}}"
    {{/each}}
  envFrom:
    - secret: altinn-admin
  env:
    - name: USE_VAULT_ENV
      value: "false"
  {{#each envs}}
    - name: "{{name}}"
      value: "{{value}}"
  {{/each}}
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
