package no.nav.altinn.admin.metrics

import io.prometheus.client.Counter

private const val NAMESPACE = "altinn_admin"

object Metrics {
    val srrExipingRules: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("expiring_rettighetsregler")
        .labelNames("sc")
        .help("Antall regler i rettighetsregister som er utgående")
        .register()
    val getRightsRequest: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("get_rights_request")
        .labelNames("sc")
        .help("Antall hent request mot rettighetsregisteret")
        .register()
    val getRightsResponse: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("get_rights_response")
        .labelNames("sc")
        .help("Antall hent response fra rettighetsregisteret")
        .register()
    val getRightsFailed: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("get_rights_failed")
        .labelNames("sc")
        .help("Antall hent failed fra rettighetsregisteret")
        .register()
    val addRightsRequest: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("add_rights_request")
        .labelNames("sc")
        .help("Antall leggtil request mot rettighetsregisteret")
        .register()
    val addRightsResponse: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("add_rights_response")
        .labelNames("sc")
        .help("Antall leggtil response fra rettighetsregisteret")
        .register()
    val addRightsFailed: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("add_rights_failed")
        .labelNames("sc")
        .help("Antall leggtil failed fra rettighetsregisteret")
        .register()
    val deleteRightsRequest: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("delete_rights_request")
        .labelNames("sc")
        .help("Antall slett request mot rettighetsregisteret")
        .register()
    val deleteRightsResponse: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("delete_rights_response")
        .labelNames("sc")
        .help("Antall slett response fra rettighetsregisteret")
        .register()
    val deleteRightsFailed: Counter = Counter.build()
        .namespace(NAMESPACE)
        .name("delete_rights_failed")
        .labelNames("sc")
        .help("Antall slett failed fra rettighetsregisteret")
        .register()
}
