<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
                  xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
                  xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
                  xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:tns="http://www.altinn.no/services/Register/SRR/2015/06"
                  xmlns:wsa10="http://www.w3.org/2005/08/addressing"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" name="RegisterSRRAgencyExternalBasicSF"
                  targetNamespace="http://www.altinn.no/services/Register/SRR/2015/06">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.altinn.no/services/2009/10"
                   elementFormDefault="qualified" targetNamespace="http://www.altinn.no/services/2009/10">
            <xs:element name="Test">
                <xs:complexType>
                    <xs:sequence/>
                </xs:complexType>
            </xs:element>
            <xs:element name="TestResponse">
                <xs:complexType>
                    <xs:sequence/>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified"
                   elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://www.altinn.no/services/common/fault/2009/10" elementFormDefault="qualified"
                   targetNamespace="http://www.altinn.no/services/common/fault/2009/10">
            <xs:complexType name="AltinnFault">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Represents a SOAP fault message used by Altinn to convey exception information to the
                            caller.
                        </summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element minOccurs="0" name="AltinnErrorMessage" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets the error message.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="AltinnExtendedErrorMessage" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets the verbose version of the error message.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="AltinnLocalizedErrorMessage" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets the localized version of the error message.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="ErrorGuid" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets the unique GUID for the specific fault.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="ErrorID" type="xs:int">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets the error type id.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="UserGuid" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets the GUID of the user.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="UserId" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets the id of the user.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="AltinnFault" nillable="true" type="tns:AltinnFault"/>
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
                   targetNamespace="http://www.altinn.no/services/Register/SRR/2015/06">
            <xs:import namespace="http://schemas.altinn.no/services/Register/SRR/2015/06"/>
            <xs:element name="GetRightsBasic">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="1" name="systemUserName" type="xs:string"/>
                        <xs:element minOccurs="1" name="systemPassword" type="xs:string"/>
                        <xs:element minOccurs="1" name="serviceCode" type="xs:string"/>
                        <xs:element minOccurs="1" name="serviceEditionCode" type="xs:int"/>
                        <xs:element minOccurs="0" name="reportee" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetRightsBasicResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q1="http://schemas.altinn.no/services/Register/SRR/2015/06" minOccurs="0"
                                    name="GetRightsBasicResult" nillable="true" type="q1:GetRightResponseList"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="AddRightsBasic">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="1" name="systemUserName" type="xs:string"/>
                        <xs:element minOccurs="1" name="systemPassword" type="xs:string"/>
                        <xs:element minOccurs="1" name="serviceCode" type="xs:string"/>
                        <xs:element minOccurs="1" name="serviceEditionCode" type="xs:int"/>
                        <xs:element xmlns:q2="http://schemas.altinn.no/services/Register/SRR/2015/06" minOccurs="1"
                                    name="insertRightList" type="q2:AddRightRequestList"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="AddRightsBasicResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q3="http://schemas.altinn.no/services/Register/SRR/2015/06" minOccurs="0"
                                    name="AddRightsBasicResult" nillable="true" type="q3:AddRightResponseList"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DeleteRightsBasic">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="1" name="systemUserName" type="xs:string"/>
                        <xs:element minOccurs="1" name="systemPassword" type="xs:string"/>
                        <xs:element minOccurs="1" name="serviceCode" type="xs:string"/>
                        <xs:element minOccurs="1" name="serviceEditionCode" type="xs:int"/>
                        <xs:element xmlns:q4="http://schemas.altinn.no/services/Register/SRR/2015/06" minOccurs="1"
                                    name="deleteRightList" type="q4:DeleteRightRequestList"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DeleteRightsBasicResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q5="http://schemas.altinn.no/services/Register/SRR/2015/06" minOccurs="0"
                                    name="DeleteRightsBasicResult" nillable="true" type="q5:DeleteRightResponseList"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://schemas.altinn.no/services/Register/SRR/2015/06" elementFormDefault="qualified"
                   targetNamespace="http://schemas.altinn.no/services/Register/SRR/2015/06">
            <xs:import namespace="http://schemas.altinn.no/services/Register/2015/06"/>
            <xs:complexType name="GetRightResponseList">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Collection of RegisterSRRGetRightResponseExternalBE objects.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="GetRightResponse" nillable="true"
                                type="tns:GetRightResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="GetRightResponseList" nillable="true" type="tns:GetRightResponseList"/>
            <xs:complexType name="GetRightResponse">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Entity for representing an entry in the Service Rights Registry.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:complexContent mixed="false">
                    <xs:extension base="tns:RegisterSRRRight">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="ValidTo" type="xs:dateTime">
                                <xs:annotation>
                                    <xs:appinfo/>
                                    <xs:documentation>
                                        <summary>Gets or sets date to which the right is valid.</summary>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="GetRightResponse" nillable="true" type="tns:GetRightResponse"/>
            <xs:complexType name="RegisterSRRRight">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Condition" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets the Condition</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="Reportee" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets Identifier used to identify a Reportee.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element xmlns:q1="http://schemas.altinn.no/services/Register/2015/06" name="Right"
                                type="q1:RegisterSRRRightsType">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary>Gets or sets the Right.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="RegisterSRRRight" nillable="true" type="tns:RegisterSRRRight"/>
            <xs:complexType name="AddRightRequestList">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Collection of RegisterSRRRightsExternalBE objects.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="AddRightRequest" nillable="true"
                                type="tns:AddRightRequest"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="AddRightRequestList" nillable="true" type="tns:AddRightRequestList"/>
            <xs:complexType name="AddRightRequest">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Entity for representing an entry in the Service Rights Registry.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:complexContent mixed="false">
                    <xs:extension base="tns:RegisterSRRRight">
                        <xs:sequence>
                            <xs:element name="ValidTo" type="xs:dateTime">
                                <xs:annotation>
                                    <xs:appinfo/>
                                    <xs:documentation>
                                        <summary>Gets or sets date to which the right is valid.</summary>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="AddRightRequest" nillable="true" type="tns:AddRightRequest"/>
            <xs:complexType name="AddRightResponseList">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Collection of RegisterSRRAddRightResponseExternalBE objects.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="AddRightResponse" nillable="true"
                                type="tns:AddRightResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="AddRightResponseList" nillable="true" type="tns:AddRightResponseList"/>
            <xs:complexType name="AddRightResponse">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Entity for representing an entry in the Service Rights Registry.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:complexContent mixed="false">
                    <xs:extension base="tns:AddRightRequest">
                        <xs:sequence>
                            <xs:element xmlns:q2="http://schemas.altinn.no/services/Register/2015/06" minOccurs="0"
                                        name="OperationResult" nillable="true" type="q2:OperationResult">
                                <xs:annotation>
                                    <xs:appinfo/>
                                    <xs:documentation>
                                        <summary>Gets or sets a result for the current operation.</summary>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="AddRightResponse" nillable="true" type="tns:AddRightResponse"/>
            <xs:complexType name="DeleteRightRequestList">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Collection of RegisterSRRDeleteRightRequestExternalBE objects.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="DeleteRightRequest" nillable="true"
                                type="tns:DeleteRightRequest"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="DeleteRightRequestList" nillable="true" type="tns:DeleteRightRequestList"/>
            <xs:complexType name="DeleteRightRequest">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Entity for representing an entry in the Service Rights Registry.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:complexContent mixed="false">
                    <xs:extension base="tns:RegisterSRRRight">
                        <xs:sequence/>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="DeleteRightRequest" nillable="true" type="tns:DeleteRightRequest"/>
            <xs:complexType name="DeleteRightResponseList">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Collection of RegisterSRRDeleteRightResponseExternalBE objects.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="DeleteRightResponse" nillable="true"
                                type="tns:DeleteRightResponse"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="DeleteRightResponseList" nillable="true" type="tns:DeleteRightResponseList"/>
            <xs:complexType name="DeleteRightResponse">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>Entity for representing an entry in the Service Rights Registry.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:complexContent mixed="false">
                    <xs:extension base="tns:DeleteRightRequest">
                        <xs:sequence>
                            <xs:element xmlns:q3="http://schemas.altinn.no/services/Register/2015/06" minOccurs="0"
                                        name="OperationResult" nillable="true" type="q3:OperationResult">
                                <xs:annotation>
                                    <xs:appinfo/>
                                    <xs:documentation>
                                        <summary>Gets or sets a result for the current operation.</summary>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="DeleteRightResponse" nillable="true" type="tns:DeleteRightResponse"/>
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://schemas.altinn.no/services/Register/2015/06" elementFormDefault="qualified"
                   targetNamespace="http://schemas.altinn.no/services/Register/2015/06">
            <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
            <xs:simpleType name="RegisterSRRRightsType">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>The right for a reportee over a Service in Service Rights Registry.</summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="None">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>None has been specified</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="Read">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>Read right</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="Write">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>Write right</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="Sign">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>Sign right</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="ArchiveRead">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>ArchiveRead right</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="ArchiveDelete">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>ArchiveDelete right</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="Access">
                        <xs:annotation>
                            <xs:appinfo>
                                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">8
                                </EnumerationValue>
                            </xs:appinfo>
                            <xs:documentation>
                                <summary>Access right</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="RegisterSRRRightsType" nillable="true" type="tns:RegisterSRRRightsType"/>
            <xs:simpleType name="OperationResult">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary>This Enum is used to return appropriate status for a operation on a particular right in
                            Service Rights Registry.
                        </summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Unknown">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>None has been specified.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="Ok">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>Rule Successfully Inserted.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="RuleNotFound">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>Rule was not found to be deleted.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="RuleAlreadyExists">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>Rule already exists in the database.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="EmptyOrNotAValidSsnOrOrganisation">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>The current Reportee is not a valid SSN or Organization.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="RightAlreadyExpired">
                        <xs:annotation>
                            <xs:documentation>
                                <summary>The right which is to be assigned has already expired.</summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="OperationResult" nillable="true" type="tns:OperationResult"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_Test_InputMessage">
        <wsdl:part xmlns:q1="http://www.altinn.no/services/2009/10" name="parameters" element="q1:Test"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_Test_OutputMessage">
        <wsdl:part xmlns:q2="http://www.altinn.no/services/2009/10" name="parameters" element="q2:TestResponse"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_Test_AltinnFaultFault_FaultMessage">
        <wsdl:part xmlns:q3="http://www.altinn.no/services/common/fault/2009/10" name="detail"
                   element="q3:AltinnFault"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_GetRightsBasic_InputMessage">
        <wsdl:part name="parameters" element="tns:GetRightsBasic"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_GetRightsBasic_OutputMessage">
        <wsdl:part name="parameters" element="tns:GetRightsBasicResponse"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_GetRightsBasic_AltinnFaultFault_FaultMessage">
        <wsdl:part xmlns:q4="http://www.altinn.no/services/common/fault/2009/10" name="detail"
                   element="q4:AltinnFault"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_AddRightsBasic_InputMessage">
        <wsdl:part name="parameters" element="tns:AddRightsBasic"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_AddRightsBasic_OutputMessage">
        <wsdl:part name="parameters" element="tns:AddRightsBasicResponse"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_AddRightsBasic_AltinnFaultFault_FaultMessage">
        <wsdl:part xmlns:q5="http://www.altinn.no/services/common/fault/2009/10" name="detail"
                   element="q5:AltinnFault"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_DeleteRightsBasic_InputMessage">
        <wsdl:part name="parameters" element="tns:DeleteRightsBasic"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_DeleteRightsBasic_OutputMessage">
        <wsdl:part name="parameters" element="tns:DeleteRightsBasicResponse"/>
    </wsdl:message>
    <wsdl:message name="IRegisterSRRAgencyExternalBasic_DeleteRightsBasic_AltinnFaultFault_FaultMessage">
        <wsdl:part xmlns:q6="http://www.altinn.no/services/common/fault/2009/10" name="detail"
                   element="q6:AltinnFault"/>
    </wsdl:message>
    <wsdl:portType name="IRegisterSRRAgencyExternalBasic">
        <wsdl:documentation>
            <summary>Service contract for the Register SRR Agency External Service. It uses the Basic Http Binding.
            </summary>
        </wsdl:documentation>
        <wsdl:operation name="Test">
            <wsdl:input wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test"
                        message="tns:IRegisterSRRAgencyExternalBasic_Test_InputMessage"/>
            <wsdl:output wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse"
                         message="tns:IRegisterSRRAgencyExternalBasic_Test_OutputMessage"/>
            <wsdl:fault wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault"
                        name="AltinnFaultFault"
                        message="tns:IRegisterSRRAgencyExternalBasic_Test_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="GetRightsBasic">
            <wsdl:documentation>
                <summary>This method calls an internal method which returns rights for a service saved in register
                    database in Service Rights Registry table for the Service code and Service Edition Code passed on as
                    inputs.
                </summary>
                <param name="systemUserName">The UserName for the calling system.</param>
                <param name="systemPassword">The password used to authenticate the calling system.</param>
                <param name="serviceCode">External Service Code of the Service.</param>
                <param name="serviceEditionCode">External Service Edition Code of the Service.</param>
                <param name="reportee">Optional reportee, If we want to know right for a reportee for a service.</param>
                <returns>Returns a list of rights with Reportee for a service using the input parameters.</returns>
            </wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/GetRightsBasic"
                    message="tns:IRegisterSRRAgencyExternalBasic_GetRightsBasic_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/GetRightsBasicResponse"
                    message="tns:IRegisterSRRAgencyExternalBasic_GetRightsBasic_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/GetRightsBasicAltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:IRegisterSRRAgencyExternalBasic_GetRightsBasic_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="AddRightsBasic">
            <wsdl:documentation>
                <summary>This method calls an internal method which in turn adds new rights for a service to the Service
                    Rights Registry table.
                </summary>
                <param name="systemUserName">The UserName for the calling system.</param>
                <param name="systemPassword">The password used to authenticate the calling system.</param>
                <param name="serviceCode">External Service Code of the Service for which rights are being added.</param>
                <param name="serviceEditionCode">External Service Edition Code of the Service for which rights are being
                    added.
                </param>
                <param name="insertRightList">Rights to be added into the register.</param>
                <returns>Returns the same list back with result of each of the operation.</returns>
            </wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/AddRightsBasic"
                    message="tns:IRegisterSRRAgencyExternalBasic_AddRightsBasic_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/AddRightsBasicResponse"
                    message="tns:IRegisterSRRAgencyExternalBasic_AddRightsBasic_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/AddRightsBasicAltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:IRegisterSRRAgencyExternalBasic_AddRightsBasic_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="DeleteRightsBasic">
            <wsdl:documentation>
                <summary>This external method calls an internal method which deletes existing rights for a service from
                    the Service Rights Registry table.
                </summary>
                <param name="systemUserName">The UserName for the calling system.</param>
                <param name="systemPassword">The password used to authenticate the calling system.</param>
                <param name="serviceCode">External Service Code of the Service for which rights are being deleted.
                </param>
                <param name="serviceEditionCode">External Service Edition Code of the Service for which rights are being
                    deleted.
                </param>
                <param name="deleteRightList">Rights to be deleted from the register.</param>
                <returns>Returns the same list back with result of each of the operation.</returns>
            </wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/DeleteRightsBasic"
                    message="tns:IRegisterSRRAgencyExternalBasic_DeleteRightsBasic_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/DeleteRightsBasicResponse"
                    message="tns:IRegisterSRRAgencyExternalBasic_DeleteRightsBasic_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/DeleteRightsBasicAltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:IRegisterSRRAgencyExternalBasic_DeleteRightsBasic_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BasicHttpBinding_IRegisterSRRAgencyExternalBasic" type="tns:IRegisterSRRAgencyExternalBasic">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Test">
            <soap:operation soapAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test"
                            style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault use="literal" name="AltinnFaultFault" namespace=""/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="GetRightsBasic">
            <soap:operation
                    soapAction="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/GetRightsBasic"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault use="literal" name="AltinnFaultFault" namespace=""/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="AddRightsBasic">
            <soap:operation
                    soapAction="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/AddRightsBasic"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault use="literal" name="AltinnFaultFault" namespace=""/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="DeleteRightsBasic">
            <soap:operation
                    soapAction="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasic/DeleteRightsBasic"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault use="literal" name="AltinnFaultFault" namespace=""/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="RegisterSRRAgencyExternalBasicSF">
        <wsdl:port name="BasicHttpBinding_IRegisterSRRAgencyExternalBasic"
                   binding="tns:BasicHttpBinding_IRegisterSRRAgencyExternalBasic">
            <soap:address location="https://www.altinn.no/RegisterExternal/RegisterSRRAgencyExternalBasic.svc"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>